apiVersion: v1
kind: Service
metadata:
  labels:
    name: mqtt-svc
  name: mqtt-svc
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 30830
  selector:
    app: mqtt-broker