apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-svc
  name: nginx-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: nginx