apiVersion: v1
kind: Service
metadata:
  labels:
    name: debian-svc
  name: debian-svc
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      nodePort: 32011
  selector:
    app: debian
---
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
  labels:
     app: debian
spec:
  containers:
  - image: debian
    command:
      - sleep
      - "3600000"
    imagePullPolicy: IfNotPresent
    name: debian
    ports:
    - containerPort: 22
  restartPolicy: Always